version: "3.8"

x-spark-common-config: &spark-common-config
  image: ${SPARK_IMAGE}:${SPARK_VERSION}
  volumes:
    - /lab/:/opt/spark/work-dir/
    - ./config/:${HADOOP_HOME}/etc/hadoop

services:
  namenode:
    image: ${HADOOP_RUNNER_IMAGE}:${HADOOP_RUNNER_VERSION}
    hostname: namenode
    command: /init/init
    volumes:
      - .:/lab/
      - /opt/hadoop/:${HADOOP_HOME}
      - ./config/:${HADOOP_HOME}/etc/hadoop
      - ./hadoop-init/:/init/
    ports:
      - 9870:9870
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9870/"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3

  spark-master:
    <<: *spark-common-config
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    <<: *spark-common-config
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    depends_on:
      - spark-master
    deploy:
      mode: replicated
      replicas: 4

  client:
    image: ghcr.io/ca4022/csc1109-lab5-client
    environment:
      - SHELL=${SHELL}
      - EDITOR=${EDITOR}
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    depends_on:
      namenode:
        condition: service_healthy
      spark-master:
        condition: service_started
    command: sleep infinity
    working_dir: /lab/
    volumes:
      - .:/lab/
    stdin_open: true
    tty: true
