version: "3.8"

x-hadoop-common-config: &hadoop-common-config
  image: ${HADOOP_RUNNER_IMAGE}:${HADOOP_RUNNER_VERSION}
  volumes:
    - .:/lab/
    - ./config:${HADOOP_HOME}/etc/hadoop
  environment:
    - HADOOP_HOME=${HADOOP_HOME}
    - HADOOP_USER_NAME=${HADOOP_USER_NAME}
    - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED

x-hive-common-config: &hive-common-config
  image: ${HIVE_IMAGE}:${HIVE_VERSION}
  volumes:
    - .:/lab/
    - ./config:${HIVE_HOME}/conf
    - ./hive_init.sh:/hive_init.sh
    - /opt/hive/lib/postgresql.jar:/opt/hive/lib/postgresql.jar

services:
  namenode:
    <<: *hadoop-common-config
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    healthcheck:
      test: ["CMD", "curl", "-f", "http://namenode:9870"]
      interval: 10s
      timeout: 5s
      retries: 5

  datanode:
    <<: *hadoop-common-config
    command: ["hdfs", "datanode"]
    deploy:
      mode: replicated
      replicas: 4
    depends_on:
      namenode:
        condition: service_healthy

  resourcemanager:
    <<: *hadoop-common-config
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    depends_on:
      namenode:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/ws/v1/cluster/info"]
      interval: 10s
      timeout: 5s
      retries: 5

  nodemanager:
    <<: *hadoop-common-config
    command: ["yarn", "nodemanager"]
    depends_on:
      resourcemanager:
        condition: service_healthy

  historyserver:
    <<: *hadoop-common-config
    hostname: historyserver
    command: ["mapred", "historyserver"]
    ports:
      - "19888:19888"
      - "10020:10020"
    depends_on:
      namenode:
        condition: service_started

  postgres:
    image: docker.io/library/postgres:12.22
    hostname: postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "PGPASSWORD=$${POSTGRES_PASSWORD} psql -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-init:
    <<: *hive-common-config
    hostname: hive-init
    entrypoint: /hive_init.sh
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HIVE_USER_NAME=${HIVE_USER_NAME}
      - HIVE_HOME=${HIVE_HOME}
    depends_on:
      postgres:
        condition: service_healthy
      namenode:
        condition: service_healthy

  metastore:
    <<: *hive-common-config
    hostname: metastore
    entrypoint: hive --skiphadoopversion --skiphbasecp --service metastore
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HIVE_HOME=${HIVE_HOME}
      - METASTORE_PORT=9083
    depends_on:
      hive-init:
        condition: service_completed_successfully
      namenode:
        condition: service_healthy
    ports:
      - "9083:9083"

  hiveserver:
    <<: *hive-common-config
    hostname: hiveserver
    entrypoint: hive --skiphadoopversion --skiphbasecp --service hiveserver2
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HIVE_HOME=${HIVE_HOME}
      - HIVESERVER2_PID_DIR=/tmp/hive
    depends_on:
      metastore:
        condition: service_started
      namenode:
        condition: service_healthy
    ports:
      - "10000:10000"

  client:
    image: ghcr.io/ca4022/csc1109-lab2-client
    hostname: client
    depends_on:
      namenode:
        condition: service_healthy
      resourcemanager:
        condition: service_started
      hiveserver:
        condition: service_started
    command: sleep infinity
    working_dir: /lab/
    volumes:
      - .:/lab/
      - ./config:${HADOOP_HOME}/etc/hadoop
      - /opt/hive:${HIVE_HOME}
      - ./config:${HIVE_HOME}/conf
    environment:
      - SHELL=${SHELL}
      - EDITOR=${EDITOR}
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
      - HIVE_HOME=${HIVE_HOME}
      - HIVE_USER_NAME=${HIVE_USER_NAME}
    stdin_open: true
    tty: true
